steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--build-arg"
      - "NEXT_PUBLIC_APP_API_KEY=$_NEXT_PUBLIC_APP_API_KEY"
      - "--build-arg"
      - "NEXT_PUBLIC_APP_APP_ID=$_NEXT_PUBLIC_APP_APP_ID"
      - "--build-arg"
      - "NEXT_PUBLIC_APP_AUTH_DOMAIN=$_NEXT_PUBLIC_APP_AUTH_DOMAIN"
      - "--build-arg"
      - "NEXT_PUBLIC_APP_MESSAGING_SENDER_ID=$_NEXT_PUBLIC_APP_MESSAGING_SENDER_ID"
      - "--build-arg"
      - "NEXT_PUBLIC_APP_PROJECT_ID=$_NEXT_PUBLIC_APP_PROJECT_ID"
      - "--build-arg"
      - "NEXT_PUBLIC_APP_STORAGE_BUCKET=$_NEXT_PUBLIC_APP_STORAGE_BUCKET"
      - "--build-arg"
      - "NEXT_PUBLIC_APP_MEASUREMENT_ID=$_NEXT_PUBLIC_APP_MEASUREMENT_ID"

      - "--build-arg"
      - "APP_PROJECT_ID=$_APP_PROJECT_ID"
      - "--build-arg"
      - "APP_PRIVATE_KEY=$_APP_PRIVATE_KEY"
      - "--build-arg"
      - "APP_CLIENT_EMAIL=$_APP_CLIENT_EMAIL"

      - "--build-arg"
      - "NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL"
      - "--build-arg"
      - "X_HASURA_ADMIN_SECRET=$_X_HASURA_ADMIN_SECRET"

      - "--build-arg"
      - "GCS_BUCKET_NAME=$_GCS_BUCKET_NAME"
      - "--build-arg"
      - "GCS_CLIENT_EMAIL=$_GCS_CLIENT_EMAIL"
      - "--build-arg"
      - "GCS_PRIVATE_KEY=$_GCS_PRIVATE_KEY"
      - "--no-cache"
      - "-t"
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - "-f"
      - Dockerfile

    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - >-
        --image=$_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_HOSTNAME: asia-northeast1-docker.pkg.dev
  _PLATFORM: managed
  _SERVICE_NAME: law-app
  _DEPLOY_REGION: asia-northeast1
  _TRIGGER_ID: c38863e4-db06-42dd-bba9-ba19a70a357b
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - law-app
