export const BLOCK_TEMPLATE = [
  {
    id: "initialBlockId",
    type: "heading",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 1 },
    content: [{ type: "text", text: "テンプレートの世界", styles: { underline: true } }],
    children: [],
  },
  {
    id: "3c46a7dd-88a0-4172-8fc9-5835eadf08ac",
    type: "paragraph",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
    content: [],
    children: [],
  },
  {
    id: "1fcf3d21-8657-4b7b-9f39-1f0eeea0d7f7",
    type: "heading",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 2 },
    content: [{ type: "text", text: "この世界を作成した理由", styles: {} }],
    children: [],
  },
  {
    id: "ad65c1dc-3475-4890-be89-7952383d4227",
    type: "paragraph",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
    content: [{ type: "text", text: "理由等あればここに", styles: {} }],
    children: [],
  },
  {
    id: "50fa15c8-3a44-4ec3-9069-6c9ef13367bc",
    type: "paragraph",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
    content: [],
    children: [],
  },
  {
    id: "5e707e71-1572-4793-96cf-43b889213a51",
    type: "heading",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 2 },
    content: [{ type: "text", text: "この世界で実現したいこと", styles: {} }],
    children: [],
  },
  {
    id: "85b24113-244b-41c7-a650-40116fad7fd8",
    type: "paragraph",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
    content: [{ type: "text", text: "実現したいことがあればここに", styles: {} }],
    children: [],
  },
  {
    id: "4f4088b9-0288-4454-a4d7-f34dc98868dd",
    type: "paragraph",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
    content: [],
    children: [],
  },
  {
    id: "49c6223d-ef55-40b9-9c5d-f39d2c63df86",
    type: "heading",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 2 },
    content: [{ type: "text", text: "この世界の鍵となる決まり", styles: {} }],
    children: [],
  },
  {
    id: "95651f8f-15a4-4be8-96ba-cb21f20512b1",
    type: "paragraph",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
    content: [{ type: "text", text: "鍵となる決まりがあればここに", styles: {} }],
    children: [],
  },
  {
    id: "ea3f1290-914a-48b6-9f18-dec95b2ac90f",
    type: "paragraph",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
    content: [],
    children: [],
  },
  {
    id: "d7f650a2-fc3a-4a88-a43b-efc8af4b108e",
    type: "heading",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left", level: 2 },
    content: [{ type: "text", text: "決まりの採用理由", styles: {} }],
    children: [],
  },
  {
    id: "7297fa27-a8b9-4a5c-bf5f-99275ca54144",
    type: "numberedListItem",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
    content: [{ type: "text", text: "テンプレートのきまり", styles: { bold: true } }],
    children: [
      {
        id: "7084ae02-ad9d-46ee-93aa-dba060eb08e6",
        type: "numberedListItem",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
        content: [{ type: "text", text: "理由", styles: {} }],
        children: [],
      },
    ],
  },
  {
    id: "ed367c87-3b4d-4a1c-98d7-dd7e7784fbec",
    type: "numberedListItem",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
    content: [{ type: "text", text: "結構いい決まり", styles: { bold: true } }],
    children: [
      {
        id: "9fcc02d1-4041-4fb1-a866-37c048fba834",
        type: "numberedListItem",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
        content: [{ type: "text", text: "理由", styles: {} }],
        children: [],
      },
    ],
  },
  {
    id: "a88e91ef-26ed-469c-994e-10938fb1532b",
    type: "numberedListItem",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
    content: [{ type: "text", text: "悪い決まり", styles: { bold: true } }],
    children: [
      {
        id: "e9024e88-905e-480a-8018-e105e3f82423",
        type: "numberedListItem",
        props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
        content: [{ type: "text", text: "理由", styles: {} }],
        children: [],
      },
    ],
  },
  {
    id: "d51bf5f6-8a98-40a7-a4d7-f21a229e1465",
    type: "paragraph",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
    content: [],
    children: [],
  },
  {
    id: "e235629e-13f5-487f-b709-f5e691bc09ad",
    type: "paragraph",
    props: { textColor: "default", backgroundColor: "default", textAlignment: "left" },
    content: [],
    children: [],
  },
];
