export const peopleNames = [
  { nativeName: "Sophia Smith", ja: "ソフィア・スミス" },
  { nativeName: "Mohammed Al-Farsi", ja: "モハメッド・アルファルシ" },
  { nativeName: "Ava Johnson", ja: "アヴァ・ジョンソン" },
  { nativeName: "Luca Rossi", ja: "ルカ・ロッシ" },
  { nativeName: "Chloe Kim", ja: "クロエ・キム" },
  { nativeName: "Liam Johnson", ja: "リアム・ジョンソン" },
  { nativeName: "Isabella Hernandez", ja: "イザベラ・エルナンデス" },
  { nativeName: "Mateo Rodriguez", ja: "マテオ・ロドリゲス" },
  { nativeName: "Olivia Wang", ja: "オリビア・ワン" },
  { nativeName: "Ethan Nguyen", ja: "イーサン・ニューウェン" },
  { nativeName: "Mia Garcia", ja: "ミア・ガルシア" },
  { nativeName: "Noah Kim", ja: "ノア・キム" },
  { nativeName: "Emma Patel", ja: "エマ・パテル" },
  { nativeName: "Sebastian Smith", ja: "セバスチャン・スミス" },
  { nativeName: "Aria Lee", ja: "アリア・リー" },
  { nativeName: "Oliver Johnson", ja: "オリバー・ジョンソン" },
  { nativeName: "Camila Martinez", ja: "カミラ・マルティネス" },
  { nativeName: "William Brown", ja: "ウィリアム・ブラウン" },
  { nativeName: "Amelia Kim", ja: "アメリア・キム" },
  { nativeName: "James Jones", ja: "ジェームズ・ジョーンズ" },
  { nativeName: "Sofia Hernandez", ja: "ソフィア・エルナンデス" },
  { nativeName: "Elijah Chang", ja: "エライジャ・チャン" },
  { nativeName: "Aiden Kim", ja: "エイデン・キム" },
  { nativeName: "Abigail Davis", ja: "アビゲイル・デイビス" },
  { nativeName: "Lucas Wang", ja: "ルーカス・ワン" },
  { nativeName: "Harper Taylor", ja: "ハーパー・テイラー" },
  { nativeName: "Daniel Martinez", ja: "ダニエル・マルティネス" },
  { nativeName: "Madison Johnson", ja: "マディソン・ジョンソン" },
  { nativeName: "Michael Kim", ja: "マイケル・キム" },
  { nativeName: "Evelyn Lee", ja: "エヴリン・リー" },
  { nativeName: "Jackson Smith", ja: "ジャクソン・スミス" },
  { nativeName: "Avery Johnson", ja: "エイブリー・ジョンソン" },
  { nativeName: "Carter Lee", ja: "カーター・リー" },
  { nativeName: "Lily Garcia", ja: "リリー・ガルシア" },
  { nativeName: "Aiden Kumar", ja: "エイデン・クマール" },
  { nativeName: "Grace Jones", ja: "グレース・ジョーンズ" },
  { nativeName: "Logan Kim", ja: "ローガン・キム" },
  { nativeName: "Aubrey Patel", ja: "オーブリー・パテル" },
  { nativeName: "Alexander Lee", ja: "アレキサンダー・リー" },
  { nativeName: "Aaliyah Johnson", ja: "アリアーナ・ジョンソン" },
  { nativeName: "Benjamin Wang", ja: "ベンジャミン・ワン" },
  { nativeName: "Zoe Smith", ja: "ゾーイ・スミス" },
  { nativeName: "Ella Kim", ja: "エラ・キム" },
  { nativeName: "Gabriel Johnson", ja: "ガブリエル・ジョンソン" },
  { nativeName: "Scarlett Davis", ja: "スカーレット・デイビス" },
  { nativeName: "Riley Kim", ja: "ライリー・キム" },
  { nativeName: "Emily Martinez", ja: "エミリー・マルティネス" },
  { nativeName: "Sebastian Brown", ja: "セバスチャン・ブラウン" },
  { nativeName: "Sophie Kim", ja: "ソフィー・キム" },
  { nativeName: "大石 一郎", ja: "ダイイシ イチロウ" },
  { nativeName: "佐藤 由美", ja: "サトウ ユミ" },
  { nativeName: "田中 太郎", ja: "タナカ タロウ" },
];
