export const IDEOLOGIES = [
  { id: "None", label: "なし", value: "0" },
  { id: "Democracy", label: "民主主義", value: "1" },
  { id: "Liberalism", label: "自由主義", value: "2" },
  { id: "Republicanism", label: "共和主義", value: "3" },
  { id: "Capitalism", label: "資本主義", value: "4" },
  { id: "Socialism", label: "社会主義", value: "5" },
  { id: "National Socialism", label: "国家社会主義", value: "6" },
  { id: "Communism", label: "共産主義", value: "7" },
  { id: "Marxism", label: "マルクス主義", value: "8" },
  { id: "Anarchism", label: "アナキズム", value: "9" },
  { id: "Libertarianism", label: "リバタリアニズム", value: "10" },
  { id: "Fascism", label: "ファシズム", value: "11" },
  { id: "Collectivism", label: "集産主義", value: "12" },
  { id: "Pacifism", label: "平和主義", value: "13" },
  { id: "Militarism", label: "軍国主義", value: "14" },
  { id: "Conservatism", label: "保守主義", value: "15" },
  { id: "Authoritarianism", label: "権威主義", value: "16" },
  { id: "Absolute Monarchy", label: "絶対主義", value: "17" },
  { id: "Dictatorship", label: "独裁主義", value: "18" },
  { id: "Totalitarianism", label: "全体主義", value: "19" },
];
